### ISSUE TITLE
Adicionar mock para Listar Disciplinas

### ISSUE THREAD

**Issue by GabrielaTMakibara** [UFABCMatricula/ufabc-sistema-matricula-server#11]
- Adicionar endpoint mockado que possibilite listar as disciplinas ofertadas, filtrando de acordo com o bacharel do aluno matriculado

**Comment by VitoriaAires** [comment]
https://github.com/UFABC-Matricula/ufabc-sistema-matricula-server/pull/6

**Comment by VitoriaAires** [comment]
https://github.com/UFABC-Matricula/ufabc-sistema-matricula-server/pull/6
